### PR TITLE
Add LayoutAnimation support

### PR DESCRIPTION
**Pull request by beretboat**
Animation duration does not seems work for now.

### CODE REVIEW

**Comment by ptmt** [comment]
Wow, thanks! Will take a deeper look later and drop some thoughts. I think we also should add support for `componentDidMount` animation to the example (it doesn't work either).

**Comment by beretboat** [comment]
Sure. Thank you!

**Comment by beretboat** [comment]
Sorry, I'm not familiar with Cocoa animation.

**Comment by ptmt** [comment]
It's ok, i will try to emulate that

**Pull request merged**
